// export const DUMMY_EXPENSES = [
//     {
//       id: "e1",
//       description: "Groceries",
//       amount: 127.53,
//       date: new Date(2024, 11, 3),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e2",
//       description: "Groceries",
//       amount: 1299.99,
//       date: new Date(2025, 0, 15),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e3",
//       description: "Groceries",
//       amount: 210.75,
//       date: new Date(2025, 1, 1),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e4",
//       description: "Health",
//       amount: 85.2,
//       date: new Date(2025, 1, 14),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e5",
//       description: "Family",
//       amount: 49.99,
//       date: new Date(2025, 1, 1),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e6",
//       description: "Family",
//       amount: 25.2,
//       date: new Date(2025, 1, 12),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e7",
//       description: "Entertainment",
//       amount: 127.53,
//       date: new Date(2024, 11, 3),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e8",
//       description: "Car",
//       amount: 1299.99,
//       date: new Date(2025, 0, 15),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e9",
//       description: "Car",
//       amount: 210.75,
//       date: new Date(2025, 1, 1),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e10",
//       description: "Education",
//       amount: 85.2,
//       date: new Date(2025, 1, 14),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e11",
//       description: "Bills",
//       amount: 49.99,
//       date: new Date(2025, 1, 1),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e12",
//       description: "Bills",
//       amount: 25.2,
//       date: new Date(2025, 1, 12),
//       comment: "Groceries",
//       type: "expense",
//     },
//     {
//       id: "e13",
//       description: "Salary",
//       amount: 2500.12,
//       date: new Date(2025, 1, 30),
//       comment: "",
//       type: "income",
//     },
//     {
//       id: "e14",
//       description: "Salary",
//       amount: 1800.20,
//       date: new Date(2025, 2, 28),
//       comment: "",
//       type: "income",
//     },
//     {
//       id: "e15",
//       description: "Gifts",
//       amount: 1800.20,
//       date: new Date(2025, 2, 15),
//       comment: "",
//       type: "income",
//     },
//     {
//       id: "e14",
//       description: "Other_income",
//       amount: 1800.20,
//       date: new Date(2025, 2, 22),
//       comment: "",
//       type: "income",
//     },
//   ];

export const DUMMY_EXPENSES = [
  {
    id: "e1",
    description: "Groceries",
    amount: 127.53,
    date: new Date(2024, 11, 3),
    comment: "Weekly Groceries",
    type: "expense",
  },
  {
    id: "e2",
    description: "Rent",
    amount: 1299.99,
    date: new Date(2025, 0, 15),
    comment: "January Rent",
    type: "expense",
  },
  {
    id: "e3",
    description: "Utilities",
    amount: 210.75,
    date: new Date(2025, 1, 1),
    comment: "February Utilities",
    type: "expense",
  },
  {
    id: "e4",
    description: "Health",
    amount: 85.2,
    date: new Date(2025, 1, 14),
    comment: "Doctor Visit",
    type: "expense",
  },
  {
    id: "e5",
    description: "Family",
    amount: 49.99,
    date: new Date(2025, 1, 1),
    comment: "Family Outing",
    type: "expense",
  },
  {
    id: "e6",
    description: "Entertainment",
    amount: 25.2,
    date: new Date(2025, 1, 12),
    comment: "Movie Tickets",
    type: "expense",
  },
  {
    id: "e7",
    description: "Dining Out",
    amount: 65.0,
    date: new Date(2024, 11, 20),
    comment: "Dinner with Friends",
    type: "expense",
  },
  {
    id: "e8",
    description: "Car Insurance",
    amount: 350.0,
    date: new Date(2025, 0, 20),
    comment: "Car Insurance Payment",
    type: "expense",
  },
  {
    id: "e9",
    description: "Gym Membership",
    amount: 50.0,
    date: new Date(2025, 1, 5),
    comment: "Monthly Gym Fee",
    type: "expense",
  },
  {
    id: "e10",
    description: "Education",
    amount: 150.0,
    date: new Date(2025, 1, 18),
    comment: "Online Course",
    type: "expense",
  },
  {
    id: "e11",
    description: "Bills",
    amount: 75.0,
    date: new Date(2025, 1, 25),
    comment: "Phone Bill",
    type: "expense",
  },
  {
    id: "e12",
    description: "Shopping",
    amount: 100.0,
    date: new Date(2025, 1, 28),
    comment: "New Clothes",
    type: "expense",
  },
  {
    id: "e13",
    description: "Salary",
    amount: 2500.12,
    date: new Date(2025, 1, 30),
    comment: "February Salary",
    type: "income",
  },
  {
    id: "e14",
    description: "Salary",
    amount: 1800.2,
    date: new Date(2025, 2, 28),
    comment: "March Salary",
    type: "income",
  },
  {
    id: "e15",
    description: "Gifts",
    amount: 100.0,
    date: new Date(2025, 2, 15),
    comment: "Birthday Gift",
    type: "income",
  },
  {
    id: "e16",
    description: "Other Income",
    amount: 500.0,
    date: new Date(2025, 2, 22),
    comment: "Freelance Work",
    type: "income",
  },
  {
    id: "e17",
    description: "Groceries",
    amount: 90.5,
    date: new Date(2024, 0, 5),
    comment: "January Groceries",
    type: "expense",
  },
  {
    id: "e18",
    description: "Entertainment",
    amount: 40.0,
    date: new Date(2024, 0, 18),
    comment: "Movie",
    type: "expense",
  },
  {
    id: "e19",
    description: "Utilities",
    amount: 110.2,
    date: new Date(2024, 2, 3),
    comment: "March Utilities",
    type: "expense",
  },
  {
    id: "e20",
    description: "Transportation",
    amount: 60.0,
    date: new Date(2024, 5, 10),
    comment: "June Transportation",
    type: "expense",
  },
  {
    id: "e21",
    description: "Shopping",
    amount: 120.0,
    date: new Date(2024, 8, 15),
    comment: "September Shopping",
    type: "expense",
  },
  {
    id: "e22",
    description: "Dining Out",
    amount: 75.5,
    date: new Date(2024, 10, 22),
    comment: "November Dinner",
    type: "expense",
  },
  {
    id: "e23",
    description: "Bonus",
    amount: 1000.0,
    date: new Date(2024, 11, 31),
    comment: "December Bonus",
    type: "income",
  },
  {
    id: "e24",
    description: "Salary",
    amount: 2500.0,
    date: new Date(2025, 0, 31),
    comment: "January Salary",
    type: "income",
  },
  {
    id: "e25",
    description: "Investments",
    amount: 300.0,
    date: new Date(2025, 2, 8),
    comment: "March Investments",
    type: "expense",
  },
  {
    id: "e51",
    description: "Salary",
    amount: 2800.0,
    date: new Date(2024, 7, 31),
    comment: "July Salary",
    type: "income",
  },
  {
    id: "e52",
    description: "Gifts",
    amount: 60.0,
    date: new Date(2025, 0, 18),
    comment: "Christmas gift",
    type: "income",
  },
  {
    id: "e53",
    description: "Other_income",
    amount: 320.0,
    date: new Date(2024, 9, 7),
    comment: "Rental income",
    type: "income",
  },
  {
    id: "e54",
    description: "Groceries",
    amount: 140.0,
    date: new Date(2025, 2, 14),
    comment: "Weekly groceries",
    type: "expense",
  },
  {
    id: "e55",
    description: "Health",
    amount: 77.0,
    date: new Date(2024, 6, 16),
    comment: "Pharmacy",
    type: "expense",
  },
  {
    id: "e56",
    description: "Family",
    amount: 98.0,
    date: new Date(2025, 1, 9),
    comment: "Family game night",
    type: "expense",
  },
  {
    id: "e57",
    description: "Entertainment",
    amount: 28.0,
    date: new Date(2024, 11, 1),
    comment: "Streaming service",
    type: "expense",
  },
  {
    id: "e58",
    description: "Car",
    amount: 180.0,
    date: new Date(2025, 0, 2),
    comment: "Car wash",
    type: "expense",
  },
  {
    id: "e59",
    description: "Education",
    amount: 125.0,
    date: new Date(2024, 8, 13),
    comment: "Online subscription",
    type: "expense",
  },
  {
    id: "e60",
    description: "Bills",
    amount: 88.0,
    date: new Date(2025, 2, 21),
    comment: "Gas bill",
    type: "expense",
  },
  {
    id: "e61",
    description: "Salary",
    amount: 3300.0,
    date: new Date(2024, 2, 28),
    comment: "March salary",
    type: "income",
  },
  {
    id: "e62",
    description: "Gifts",
    amount: 72.0,
    date: new Date(2025, 1, 25),
    comment: "Anniversary gift",
    type: "income",
  },
  {
    id: "e63",
    description: "Other_income",
    amount: 290.0,
    date: new Date(2024, 4, 11),
    comment: "Investment profit",
    type: "income",
  },
  {
    id: "e64",
    description: "Groceries",
    amount: 105.0,
    date: new Date(2025, 0, 29),
    comment: "Monthly food",
    type: "expense",
  },
  {
    id: "e65",
    description: "Health",
    amount: 44.0,
    date: new Date(2024, 5, 4),
    comment: "Vitamin supplement",
    type: "expense",
  },
  {
    id: "e66",
    description: "Family",
    amount: 67.0,
    date: new Date(2025, 2, 5),
    comment: "Family events",
    type: "expense",
  },
  {
    id: "e67",
    description: "Entertainment",
    amount: 144.0,
    date: new Date(2024, 10, 25),
    comment: "Musical show",
    type: "expense",
  },
  {
    id: "e68",
    description: "Car",
    amount: 242.0,
    date: new Date(2025, 1, 3),
    comment: "Insurance renewals",
    type: "expense",
  },
  {
    id: "e69",
    description: "Education",
    amount: 88.0,
    date: new Date(2024, 0, 9),
    comment: "Certification cost",
    type: "expense",
  },
  {
    id: "e70",
    description: "Bills",
    amount: 24.0,
    date: new Date(2025, 2, 1),
    comment: "Mobile data",
    type: "expense",
  },
  {
    id: "e71",
    description: "Salary",
    amount: 3123.0,
    date: new Date(2024, 9, 30),
    comment: "October salary",
    type: "income",
  },
  {
    id: "e72",
    description: "Gifts",
    amount: 133.0,
    date: new Date(2025, 0, 3),
    comment: "New year gift",
    type: "income",
  },
  {
    id: "e73",
    description: "Other_income",
    amount: 400.0,
    date: new Date(2024, 3, 19),
    comment: "Part time",
    type: "income",
  },
  {
    id: "e74",
    description: "Groceries",
    amount: 101.0,
    date: new Date(2025, 1, 11),
    comment: "Monthly",
    type: "expense",
  },
  {
    id: "e75",
    description: "Health",
    amount: 55.0,
    date: new Date(2024, 7, 21),
    comment: "Medical bill",
    type: "expense",
  },
  {
    id: "e76",
    description: "Family",
    amount: 78.0,
    date: new Date(2025, 2, 13),
    comment: "Activities",
    type: "expense",
  },
  {
    id: "e77",
    description: "Entertainment",
    amount: 234.0,
    date: new Date(2024, 0, 27),
    comment: "Live concert",
    type: "expense",
  },
  {
    id: "e78",
    description: "Car",
    amount: 100.0,
    date: new Date(2025, 0, 8),
    comment: "Fuel",
    type: "expense",
  },
  {
    id: "e79",
    description: "Education",
    amount: 121.0,
    date: new Date(2024, 1, 15),
    comment: "Tuition fee",
    type: "expense",
  },
  {
    id: "e80",
    description: "Bills",
    amount: 99.0,
    date: new Date(2025, 1, 28),
    comment: "House rent",
    type: "expense",
  },
  {
    id: "e81",
    description: "Salary",
    amount: 3400.0,
    date: new Date(2024, 11, 31),
    comment: "December salary",
    type: "income",
  },
  {
    id: "e82",
    description: "Gifts",
    amount: 89.0,
    date: new Date(2025, 2, 7),
    comment: "Wedding gift",
    type: "income",
  },
  {
    id: "e83",
    description: "Other_income",
    amount: 350.0,
    date: new Date(2024, 6, 28),
    comment: "Consulting fee",
    type: "income",
  },
  {
    id: "e84",
    description: "Groceries",
    amount: 112.0,
    date: new Date(2025, 2, 3),
    comment: "Weekend grocery",
    type: "expense",
  },
  {
    id: "e85",
    description: "Health",
    amount: 62.0,
    date: new Date(2024, 8, 30),
    comment: "Supplements",
    type: "expense",
  },
  {
    id: "e86",
    description: "Family",
    amount: 84.0,
    date: new Date(2025, 0, 16),
    comment: "Family trips",
    type: "expense",
  },
  {
    id: "e87",
    description: "Entertainment",
    amount: 22.0,
    date: new Date(2024, 2, 22),
    comment: "Snacks",
    type: "expense",
  },
  {
    id: "e88",
    description: "Car",
    amount: 191.0,
    date: new Date(2025, 2, 23),
    comment: "Maintenance",
    type: "expense",
  },
  {
    id: "e89",
    description: "Education",
    amount: 145.0,
    date: new Date(2024, 10, 8),
    comment: "School",
    type: "expense",
  },
  {
    id: "e90",
    description: "Bills",
    amount: 93.0,
    date: new Date(2025, 1, 14),
    comment: "Rent",
    type: "expense",
  },
  {
    id: "e91",
    description: "Salary",
    amount: 2950.0,
    date: new Date(2024, 5, 30),
    comment: "June salary",
    type: "income",
  },
  {
    id: "e92",
    description: "Gifts",
    amount: 155.0,
    date: new Date(2025, 2, 18),
    comment: "Easter gift",
    type: "income",
  },
  {
    id: "e93",
    description: "Other_income",
    amount: 420.0,
    date: new Date(2024, 1, 6),
    comment: "Dividends",
    type: "income",
  },
  {
    id: "e94",
    description: "Groceries",
    amount: 130.0,
    date: new Date(2024, 1, 7),
    comment: "groceries",
    type: "expense",
  },
  {
    id: "e95",
    description: "Health",
    amount: 87.0,
    date: new Date(2025, 0, 6),
    comment: "pharmacy",
    type: "expense",
  },
  {
    id: "e96",
    description: "Family",
    amount: 34.0,
    date: new Date(2024, 3, 8),
    comment: "entertainment",
    type: "expense",
  },
  {
    id: "e97",
    description: "Entertainment",
    amount: 156.0,
    date: new Date(2025, 2, 8),
    comment: "movies",
    type: "expense",
  },
  {
    id: "e98",
    description: "Car",
    amount: 234.0,
    date: new Date(2024, 6, 9),
    comment: "repair",
    type: "expense",
  },
  {
    id: "e99",
    description: "Education",
    amount: 178.0,
    date: new Date(2025, 2, 9),
    comment: "books",
    type: "expense",
  },
  {
    id: "e100",
    description: "Bills",
    amount: 189.0,
    date: new Date(2024, 7, 10),
    comment: "electricity",
    type: "expense",
  },
  {
    id: "e101",
    description: "Groceries",
    amount: 75.5,
    date: new Date(2024, 0, 3), // January
    comment: "Weekly groceries",
    type: "expense",
  },
  {
    id: "e102",
    description: "Entertainment",
    amount: 30.0,
    date: new Date(2024, 0, 15), // January
    comment: "Movie night",
    type: "expense",
  },
  {
    id: "e103",
    description: "Health",
    amount: 100.0,
    date: new Date(2024, 1, 7), // February
    comment: "Doctor's visit",
    type: "expense",
  },
  {
    id: "e104",
    description: "Family",
    amount: 50.0,
    date: new Date(2024, 1, 20), // February
    comment: "Family dinner",
    type: "expense",
  },
  {
    id: "e105",
    description: "Bills",
    amount: 120.0,
    date: new Date(2024, 2, 1), // March
    comment: "Electricity bill",
    type: "expense",
  },
  {
    id: "e106",
    description: "Car",
    amount: 80.0,
    date: new Date(2024, 2, 14), // March
    comment: "Gasoline",
    type: "expense",
  },
  {
    id: "e107",
    description: "Groceries",
    amount: 90.0,
    date: new Date(2024, 3, 5), // April
    comment: "Organic food",
    type: "expense",
  },
  {
    id: "e108",
    description: "Entertainment",
    amount: 60.0,
    date: new Date(2024, 3, 22), // April
    comment: "Concert tickets",
    type: "expense",
  },
  {
    id: "e109",
    description: "Health",
    amount: 40.0,
    date: new Date(2024, 4, 3), // May
    comment: "Prescription",
    type: "expense",
  },
  {
    id: "e110",
    description: "Family",
    amount: 70.0,
    date: new Date(2024, 4, 18), // May
    comment: "Weekend getaway",
    type: "expense",
  },
  {
    id: "e111",
    description: "Bills",
    amount: 95.0,
    date: new Date(2024, 5, 10), // June
    comment: "Internet bill",
    type: "expense",
  },
  {
    id: "e112",
    description: "Car",
    amount: 150.0,
    date: new Date(2024, 5, 25), // June
    comment: "Car maintenance",
    type: "expense",
  },
  {
    id: "e113",
    description: "Groceries",
    amount: 80.0,
    date: new Date(2024, 6, 12), // July
    comment: "Summer BBQ",
    type: "expense",
  },
  {
    id: "e114",
    description: "Entertainment",
    amount: 45.0,
    date: new Date(2024, 6, 28), // July
    comment: "Theme park",
    type: "expense",
  },
  {
    id: "e115",
    description: "Health",
    amount: 55.0,
    date: new Date(2024, 7, 2), // August
    comment: "Gym membership",
    type: "expense",
  },
  {
    id: "e116",
    description: "Family",
    amount: 65.0,
    date: new Date(2024, 7, 21), // August
    comment: "Family vacation",
    type: "expense",
  },
  {
    id: "e117",
    description: "Bills",
    amount: 110.0,
    date: new Date(2024, 8, 5), // September
    comment: "Water bill",
    type: "expense",
  },
  {
    id: "e118",
    description: "Car",
    amount: 75.0,
    date: new Date(2024, 8, 30), // September
    comment: "Car wash",
    type: "expense",
  },
  {
    id: "e119",
    description: "Groceries",
    amount: 105.0,
    date: new Date(2024, 9, 15), // October
    comment: "Fall harvest",
    type: "expense",
  },
  {
    id: "e120",
    description: "Entertainment",
    amount: 50.0,
    date: new Date(2024, 9, 29), // October
    comment: "Halloween party",
    type: "expense",
  },
  {
    id: "e121",
    description: "Health",
    amount: 35.0,
    date: new Date(2024, 10, 8), // November
    comment: "Flu shot",
    type: "expense",
  },
  {
    id: "e122",
    description: "Family",
    amount: 85.0,
    date: new Date(2024, 10, 24), // November
    comment: "Thanksgiving dinner",
    type: "expense",
  },
  {
    id: "e123",
    description: "Bills",
    amount: 130.0,
    date: new Date(2024, 11, 1), // December
    comment: "Gas bill",
    type: "expense",
  },
  {
    id: "e124",
    description: "Car",
    amount: 200.0,
    date: new Date(2024, 11, 20), // December
    comment: "Christmas gifts",
    type: "expense",
  },
  {
    id: "e125",
    description: "Salary",
    amount: 2700.0,
    date: new Date(2024, 0, 31), // January
    comment: "January salary",
    type: "income",
  },
  {
    id: "e126",
    description: "Other_income",
    amount: 150.0,
    date: new Date(2024, 0, 5), // January
    comment: "Freelance work",
    type: "income",
  },
  {
    id: "e127",
    description: "Salary",
    amount: 2800.0,
    date: new Date(2024, 1, 29), // February
    comment: "February salary",
    type: "income",
  },
  {
    id: "e128",
    description: "Gifts",
    amount: 60.0,
    date: new Date(2024, 1, 14), // February
    comment: "Valentine's gift",
    type: "income",
  },
  {
    id: "e129",
    description: "Salary",
    amount: 2900.0,
    date: new Date(2024, 2, 29), // March
    comment: "March salary",
    type: "income",
  },
  {
    id: "e130",
    description: "Other_income",
    amount: 200.0,
    date: new Date(2024, 2, 22), // March
    comment: "Dividends",
    type: "income",
  },
  {
    id: "e131",
    description: "Salary",
    amount: 3000.0,
    date: new Date(2024, 3, 30), // April
    comment: "April salary",
    type: "income",
  },
  {
    id: "e132",
    description: "Gifts",
    amount: 70.0,
    date: new Date(2024, 3, 1), // April
    comment: "Birthday gift",
    type: "income",
  },
  {
    id: "e133",
    description: "Salary",
    amount: 3100.0,
    date: new Date(2024, 4, 31), // May
    comment: "May salary",
    type: "income",
  },
  {
    id: "e134",
    description: "Other_income",
    amount: 250.0,
    date: new Date(2024, 4, 15), // May
    comment: "Rental income",
    type: "income",
  },
  {
    id: "e135",
    description: "Salary",
    amount: 3200.0,
    date: new Date(2024, 5, 30), // June
    comment: "June salary",
    type: "income",
  },
  {
    id: "e136",
    description: "Gifts",
    amount: 80.0,
    date: new Date(2024, 5, 8), // June
    comment: "Wedding gift",
    type: "income",
  },
  {
    id: "e137",
    description: "Salary",
    amount: 3300.0,
    date: new Date(2024, 6, 31), // July
    comment: "July salary",
    type: "income",
  },
  {
    id: "e138",
    description: "Other_income",
    amount: 300.0,
    date: new Date(2024, 6, 20), // July
    comment: "Bonus",
    type: "income",
  },
  {
    id: "e139",
    description: "Salary",
    amount: 3400.0,
    date: new Date(2024, 7, 31), // August
    comment: "August salary",
    type: "income",
  },
  {
    id: "e140",
    description: "Gifts",
    amount: 90.0,
    date: new Date(2024, 7, 10), // August
    comment: "Anniversary gift",
    type: "income",
  },
  {
    id: "e141",
    description: "Salary",
    amount: 3500.0,
    date: new Date(2024, 8, 30), // September
    comment: "September salary",
    type: "income",
  },
  {
    id: "e142",
    description: "Other_income",
    amount: 350.0,
    date: new Date(2024, 8, 15), // September
    comment: "Investment income",
    type: "income",
  },
  {
    id: "e143",
    description: "Salary",
    amount: 3600.0,
    date: new Date(2024, 9, 31), // October
    comment: "October salary",
    type: "income",
  },
  {
    id: "e144",
    description: "Gifts",
    amount: 100.0,
    date: new Date(2024, 9, 5), // October
    comment: "Halloween gift",
    type: "income",
  },
  {
    id: "e145",
    description: "Salary",
    amount: 3700.0,
    date: new Date(2024, 10, 30), // November
    comment: "November salary",
    type: "income",
  },
  {
    id: "e146",
    description: "Other_income",
    amount: 400.0,
    date: new Date(2024, 10, 12), // November
    comment: "Freelance income",
    type: "income",
  },
  {
    id: "e147",
    description: "Salary",
    amount: 3800.0,
    date: new Date(2024, 11, 31), // December
    comment: "December salary",
    type: "income",
  },
  {
    id: "e148",
    description: "Gifts",
    amount: 150.0,
    date: new Date(2024, 11, 25), // December
    comment: "Christmas gift",
    type: "income",
  },
  {
    id: "e149",
    description: "Education",
    amount: 165.0,
    date: new Date(2024, 4, 18), //May
    comment: "Books",
    type: "expense",
  },
  {
    id: "e150",
    description: "Family",
    amount: 76.0,
    date: new Date(2024, 6, 17), //July
    comment: "Trip",
    type: "expense",
  },
  {
    id: "e151",
    description: "Groceries",
    amount: 115.0,
    date: new Date(2025, 0, 7), // January
    comment: "Weekly shop",
    type: "expense",
  },
  {
    id: "e152",
    description: "Entertainment",
    amount: 42.5,
    date: new Date(2025, 0, 19), // January
    comment: "Cinema tickets",
    type: "expense",
  },
  {
    id: "e153",
    description: "Health",
    amount: 28.0,
    date: new Date(2025, 0, 25), // January
    comment: "Supplements",
    type: "expense",
  },
  {
    id: "e154",
    description: "Car",
    amount: 95.0,
    date: new Date(2025, 0, 12), // January
    comment: "Fuel",
    type: "expense",
  },
  {
    id: "e155",
    description: "Bills",
    amount: 145.0,
    date: new Date(2025, 0, 3), // January
    comment: "Rent payment",
    type: "expense",
  },
  {
    id: "e156",
    description: "Groceries",
    amount: 92.0,
    date: new Date(2025, 1, 4), // February
    comment: "Organic produce",
    type: "expense",
  },
  {
    id: "e157",
    description: "Entertainment",
    amount: 68.0,
    date: new Date(2025, 1, 16), // February
    comment: "Concert",
    type: "expense",
  },
  {
    id: "e158",
    description: "Health",
    amount: 33.5,
    date: new Date(2025, 1, 22), // February
    comment: "Prescription refill",
    type: "expense",
  },
  {
    id: "e159",
    description: "Car",
    amount: 110.0,
    date: new Date(2025, 1, 9), // February
    comment: "Car insurance",
    type: "expense",
  },
  {
    id: "e160",
    description: "Bills",
    amount: 78.5,
    date: new Date(2025, 1, 2), // February
    comment: "Internet",
    type: "expense",
  },
];
